FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:latest
WORKDIR /usr/src/app
RUN apt-get update && \
    apt-get install -yq --no-install-recommends dnsmasq iptables dnsutils
COPY wifi-to-eth-route.sh ./
CMD ["bash", "wifi-to-eth-route.sh"]